# Generated by Django 4.2.13 on 2024-05-22 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("token", models.CharField(max_length=255)),
                ("user_type", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Announcements",
            fields=[
                (
                    "announcement_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("when_date", models.DateTimeField()),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("published", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("employee_id", models.AutoField(primary_key=True, serialize=False)),
                ("lastname", models.CharField(max_length=255)),
                ("firstname", models.CharField(max_length=255)),
                ("middlename", models.CharField(max_length=255)),
                ("ranks", models.CharField(max_length=255)),
                ("assignment_level", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Events",
            fields=[
                ("event_id", models.AutoField(primary_key=True, serialize=False)),
                ("event_date", models.DateTimeField()),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("published", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="MobileScanUsers",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("account_name", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="StaticTime",
            fields=[
                ("time_id", models.AutoField(primary_key=True, serialize=False)),
                ("employee_type", models.CharField(max_length=255)),
                ("am_in", models.DateTimeField()),
                ("am_out", models.DateTimeField()),
                ("pm_in", models.DateTimeField()),
                ("pm_out", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                ("attendance_id", models.AutoField(primary_key=True, serialize=False)),
                ("date_log", models.DateTimeField()),
                ("am_in", models.DateTimeField()),
                ("am_in_mask", models.BooleanField()),
                ("am_out", models.DateTimeField()),
                ("am_out_mask", models.BooleanField()),
                ("pm_in", models.DateTimeField()),
                ("pm_in_mask", models.BooleanField()),
                ("pm_out", models.DateTimeField()),
                ("pm_out_mask", models.BooleanField()),
                ("remarks", models.CharField(max_length=255)),
                (
                    "leave_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "Annual leave"),
                            ("S", "Sick leave"),
                            ("E", "Emergency leave"),
                            ("H", "Holiday leave"),
                            ("M", "Maternity Leave"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("leave_reason", models.TextField()),
                (
                    "employee_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attendance.employee",
                    ),
                ),
            ],
        ),
    ]
